import { loadSite, loadAllSites } from "@/lib/data/sites";
import { getConsultation } from "@/lib/store";
import { evaluateDataset } from "@/lib/service";
import { rankBottlenecks } from "@/lib/matcher/soften";
import { estimateFeasibility } from "@/lib/feasibility";
import { HERO_META } from "@/data/hero-protocol";
import { TopBar, CohortBar, CohortLegend } from "@/components/ui";
import { PrintButton } from "@/components/PrintButton";

export const dynamic = "force-dynamic";

export default async function ScorecardPage({
  searchParams,
}: {
  searchParams: Promise<{ site?: string }>;
}) {
  const { site } = await searchParams;
  const siteId = site ?? loadAllSites()[0].site.id;
  const consultation = getConsultation(HERO_META.id);
  const ds = loadSite(siteId);

  if (!consultation) {
    return (
      <>
        <TopBar />
        <main className="wrap">
          <p>No consultation seeded. Run <code>npm run db:seed</code>.</p>
        </main>
      </>
    );
  }

  const evaluated = evaluateDataset(ds, consultation.criteria);
  const { counts } = evaluated;
  const bottleneck = rankBottlenecks(ds.patients, consultation.criteria)[0];
  const feas = estimateFeasibility({
    definite: counts.definite,
    possible: counts.possible,
    monthlyIncidence: ds.site.monthlyIncidence,
    months: 6,
  });

  return (
    <>
      <TopBar />
      <main className="wrap">
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 }}>
          <h1 style={{ margin: 0 }}>Feasibility scorecard</h1>
          <PrintButton />
        </div>
        <p className="muted" style={{ marginTop: 4 }}>
          {ds.site.name} — {ds.site.city}, {ds.site.country}
        </p>

        <div className="card">
          <h2>{consultation.title}</h2>
          <p className="sub">
            Sponsor {consultation.sponsorName} · ref {consultation.nct}
          </p>
          <div style={{ margin: "12px 0" }}>
            <CohortBar definite={counts.definite} possible={counts.possible} excluded={counts.excluded} />
            <CohortLegend />
          </div>
        </div>

        <div className="grid2">
          <div className="card">
            <h2>Candidate pool</h2>
            <table className="data">
              <tbody>
                <tr><td>Confirmed-eligible (definite)</td><td className="num"><strong>{counts.definite}</strong></td></tr>
                <tr><td>Possible (needs a test/confirmation)</td><td className="num"><strong>{counts.possible}</strong></td></tr>
                <tr><td>Screening pool</td><td className="num">{counts.definite + counts.possible}</td></tr>
                <tr><td>Records reviewed</td><td className="num">{counts.total}</td></tr>
              </tbody>
            </table>
          </div>
          <div className="card">
            <h2>Deliverable estimate</h2>
            <table className="data">
              <tbody>
                <tr><td>Monthly incidence (rate)</td><td className="num">{ds.site.monthlyIncidence}/mo</td></tr>
                <tr><td>Incident over 6 months</td><td className="num">{feas.incidentOverWindow}</td></tr>
                <tr><td>Screen-to-enrol funnel</td><td className="num">×{feas.screenToEnroll}</td></tr>
                <tr><td>≈ enrollable over 6 months</td><td className="num"><strong>~{feas.enrollableEstimate}</strong></td></tr>
              </tbody>
            </table>
            <p className="muted" style={{ fontSize: 12, marginTop: 8 }}>
              A chart match is an upper bound — this is discounted and rate-aware.
            </p>
          </div>
        </div>

        <div className="card">
          <h2>Biggest bottleneck</h2>
          <p>
            The criterion limiting this site most is{" "}
            <strong>{bottleneck?.label}</strong> — relaxing it would add{" "}
            {bottleneck ? bottleneck.newlyDefinite + bottleneck.newlyPossible : 0} candidates
            ({bottleneck?.newlyDefiniteFromUnknown ?? 0} of them only because the field is currently unknown).
          </p>
        </div>

        <p className="muted" style={{ fontSize: 12 }}>
          Generated by TrialBridge (Elegível). Counts only — no patient rows.
          Synthetic/de-identified data; {consultation.sourceNote}
        </p>
      </main>
    </>
  );
}
